version: '3'

services:

  db:
    restart: always
    image: mariadb
    volumes:
      - souschef_data:/var/lib/mysql
    networks:
      - backend

  web:
    environment:
      - SOUSCHEF_VERSION=v1.0-beta
    restart: always
    build: .
    volumes:
      - souschef_static:/code/src/static
    depends_on:
      - db
    networks:
      - backend

volumes:
  souschef_data:
  souschef_static:

networks:
  frontend:
  backend:
